name: action.yml demo
 
on:
  push:
  issue_comment:
    types: [created, deleted]
  issues:
    types: [opened, edited, milestoned]
 
jobs:
  # 通过 Actions 插件获取密码
  abcdefg:
    runs-on: [self-hosted]
    steps:
    - id: step1
      name: step1
      uses: shterm/pam-obtain@v1
      with:
        app-id: "test"
        user-name: "root"
        asset-name: "resource"
        connect-host: "10.13.1.2"
        credential: ${{ secrets.PAM_TOKEN }}
    - id: step2
      name: step2
      run: >
        docker run registry.cn-hangzhou.aliyuncs.com/hos_test/mysql-client
        mysql -u root
        -p${{ env.password }}
        -h 8.221.143.170
        -P 3306
        -e "show databases;"
